"""Legacy presentation defaults plus supported component metadata."""
STYLE = {'colors': {'GEOM_CONTACT': '#C2185B',
            'GEOM_SHAPE': '#8D8D8D',
            'STRUCT': '#1A237E',
            'CONTACT_ENV': '#C1272D',
            'CONN': '#00695C',
            'CONN_BLUE': '#1565C0',
            'CONTACT_VIA_CONN': '#6A1B9A',
            'PIPE': '#455A64',
            'MASS': '#6A1B9A',
            'DIM': '0.25',
            'DEEPEST': '#B71C1C',
            'AMBIG': '#F9A825',
            'WARNING': '#B71C1C',
            'CLIPPED': '#B3261E'},
 'component_colors': {'GD-ST': '#1C7FD6',
                      'GD-SB': '#8A9A2B',
                      'GD-TP': '#B0641E',
                      'GD-TT': '#7FA8C9',
                      'GD-SH': '#3E8E7E',
                      'GD-VLV': '#8E6C3E',
                      'GD-B': '#5D6D7E',
                      'GD-BOSS': '#A05A92'},
 'fonts': {'annotation': 8,
           'small': 7.5,
           'dimension': 8.5,
           'component_label': 9,
           'title': 11,
           'assembly_table': 7.4,
           'exclusions': 6.2},
 'line_widths': {'stroke_0': 0.0,
                 'stroke_0_9': 0.9,
                 'stroke_1_0': 1.0,
                 'stroke_1_1': 1.1,
                 'stroke_1_9': 1.9,
                 'stroke_2_0': 2.0,
                 'stroke_2': 2.0,
                 'stroke_2_4': 2.4,
                 'stroke_3_0': 3.0,
                 'stroke_3_4': 3.4,
                 'stroke_5_0': 5.0},
 'figure': {'component_width': 13.0, 'assembly_width': 15.0, 'export_dpi': 150},
 'labels': {'format': 'code'},
 'connector': {'foreground': 'black',
               'background': 'white',
               'symbols': {'F': 'F', 'P': 'P', 'S': 'S', 'D': 'D'}}}
CATALOG = {'schema_version': 1,
 'components': [{'component_code': 'GD-HdPipe',
                 'display_name': 'Header Pipe',
                 'ontology_source': 'knowledge/edes/EDES_GD-HdPipe_KNOWLEDGE.json',
                 'component_family': 'component',
                 'renderer': 'accessor_renderer',
                 'label_priority': 'medium',
                 'default_style_key': 'GD-HdPipe',
                 'supports_component_plot': True,
                 'supports_assembly_plot': True},
                {'component_code': 'GD-BrPipe',
                 'display_name': 'Branch Pipe',
                 'ontology_source': 'knowledge/edes/EDES_GD-BrPipe_KNOWLEDGE.json',
                 'component_family': 'component',
                 'renderer': 'accessor_renderer',
                 'label_priority': 'medium',
                 'default_style_key': 'GD-BrPipe',
                 'supports_component_plot': True,
                 'supports_assembly_plot': True},
                {'component_code': 'GD-TP',
                 'display_name': 'Thick Pipe',
                 'ontology_source': 'knowledge/edes/EDES_GD-TP_KNOWLEDGE.json',
                 'component_family': 'component',
                 'renderer': 'accessor_renderer',
                 'label_priority': 'medium',
                 'default_style_key': 'GD-TP',
                 'supports_component_plot': True,
                 'supports_assembly_plot': True},
                {'component_code': 'GD-TT',
                 'display_name': 'Tapered Thick Pipe',
                 'ontology_source': 'knowledge/edes/EDES_GD-TT_KNOWLEDGE.json',
                 'component_family': 'component',
                 'renderer': 'accessor_renderer',
                 'label_priority': 'medium',
                 'default_style_key': 'GD-TT',
                 'supports_component_plot': True,
                 'supports_assembly_plot': True},
                {'component_code': 'GD-SH',
                 'display_name': 'Shroud',
                 'ontology_source': 'knowledge/edes/EDES_GD-SH_KNOWLEDGE.json',
                 'component_family': 'component',
                 'renderer': 'accessor_renderer',
                 'label_priority': 'medium',
                 'default_style_key': 'GD-SH',
                 'supports_component_plot': True,
                 'supports_assembly_plot': True},
                {'component_code': 'GD-PIP',
                 'display_name': 'Pipe-in-Pipe Bulkhead',
                 'ontology_source': 'knowledge/edes/EDES_GD-PIP_KNOWLEDGE.json',
                 'component_family': 'component',
                 'renderer': 'accessor_renderer',
                 'label_priority': 'medium',
                 'default_style_key': 'GD-PIP',
                 'supports_component_plot': True,
                 'supports_assembly_plot': True},
                {'component_code': 'GD-VLV',
                 'display_name': 'Valve',
                 'ontology_source': 'knowledge/edes/EDES_GD-VLV_KNOWLEDGE.json',
                 'component_family': 'component',
                 'renderer': 'accessor_renderer',
                 'label_priority': 'medium',
                 'default_style_key': 'GD-VLV',
                 'supports_component_plot': True,
                 'supports_assembly_plot': True},
                {'component_code': 'GD-ST',
                 'display_name': 'Top Structure',
                 'ontology_source': 'knowledge/edes/EDES_GD-ST_KNOWLEDGE.json',
                 'component_family': 'external_structure',
                 'renderer': 'accessor_renderer',
                 'label_priority': 'medium',
                 'default_style_key': 'GD-ST',
                 'supports_component_plot': True,
                 'supports_assembly_plot': True},
                {'component_code': 'GD-SB',
                 'display_name': 'Base Structure',
                 'ontology_source': 'knowledge/edes/EDES_GD-SB_KNOWLEDGE.json',
                 'component_family': 'external_structure',
                 'renderer': 'accessor_renderer',
                 'label_priority': 'medium',
                 'default_style_key': 'GD-SB',
                 'supports_component_plot': True,
                 'supports_assembly_plot': True},
                {'component_code': 'GD-B',
                 'display_name': 'Branch Piping Assembly',
                 'ontology_source': 'knowledge/edes/EDES_GD-B_KNOWLEDGE.json',
                 'component_family': 'branch_assembly',
                 'renderer': 'accessor_renderer',
                 'label_priority': 'medium',
                 'default_style_key': 'GD-B',
                 'supports_component_plot': True,
                 'supports_assembly_plot': True},
                {'component_code': 'GD-Con',
                 'display_name': 'Connector',
                 'ontology_source': 'knowledge/edes/EDES_GD-Con_KNOWLEDGE.json',
                 'component_family': 'component',
                 'renderer': 'accessor_renderer',
                 'label_priority': 'medium',
                 'default_style_key': 'GD-Con',
                 'supports_component_plot': True,
                 'supports_assembly_plot': True},
                {'component_code': 'GD-BOSS',
                 'display_name': 'Boss',
                 'ontology_source': 'knowledge/edes/EDES_GD-BOSS_KNOWLEDGE.json',
                 'component_family': 'coaxial_sleeve',
                 'renderer': 'accessor_renderer',
                 'label_priority': 'medium',
                 'default_style_key': 'GD-BOSS',
                 'supports_component_plot': True,
                 'supports_assembly_plot': True}]}
